# Generated by Django 2.0.1 on 2018-02-18 02:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userusageinfo',
            name='files_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
