# Generated by Django 2.0.1 on 2018-02-22 22:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20180218_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusageinfo',
            name='files_hash_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
