# Generated by Django 2.0.1 on 2018-02-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_userusageinfo_files_hash_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusageinfo',
            name='data_available_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
